version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    volumes:
      - ./storage/:/app/storage
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    container_name: log_app
  mongodb:
    image: mongo:3.6-xenial
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    restart: always
    ports:
      - 27010:27017
    volumes:
      - ./storage/logs/mongodb:/var/lib/mongodb
      - ./mongod.conf:/etc/mongod.conf.orig
    container_name: mongodb
